// <auto-generated />
namespace CondSys.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CampoTitulo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CampoTitulo));
        
        string IMigrationMetadata.Id
        {
            get { return "201811200134317_CampoTitulo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
